name: Deploy EC2 with Terraform

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Global environment variables for AWS credentials
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      INSTANCE_ID: "i-0206d29fc8c855726"  # 🔁 Replace with your real EC2 instance ID

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      # - name: Terraform destroy 
      #   run: terraform destroy -auto-approve

      - name: Import Existing EC2 Instance
        run: terraform import aws_instance.example $INSTANCE_ID

      - name: Destroy EC2 Instance
        run: terraform destroy -target=aws_instance.example -auto-approve