name: Deploy EC2 with Terraform

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Global environment variables for AWS credentials
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #INSTANCE_ID: "i-006030cad72d638cd" # Replace with your real EC2 instance ID

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      - name: Import AWS Resources
        run: |
          terraform import aws_instance.testec2 i-01073063b997164d3
          terraform import aws_vpc.testvpc vpc-0feb3b054a4f4645a
          terraform import aws_subnet.testsubnet subnet-0b97233f36772c944
          terraform import aws_security_group.testsg sg-04e7e349be66616b6
          terraform import aws_internet_gateway.testigw igw-0fabd30622d451d86
          terraform import aws_route_table.testrt rtb-0df68cf8a723f1bf8

      - name: Terraform destroy 
        run: terraform destroy -auto-approve

      # - name: Import Existing EC2 Instance
      #   run: terraform import aws_instance.testec2 $INSTANCE_ID

      # - name: Destroy EC2 Instance
      #   run: terraform destroy -target=aws_instance.testec2s -auto-approve